### ISSUE TITLE
x-rh-identity causes an error about missing user

### ISSUE THREAD

**Issue by mkanoor** [RedHatInsights/insights-rbac#90]
**Describe the bug**
When trying to connect to the RBAC service to get roles in the QE environment with the we get
the following error

Traceback (most recent call last):
--
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  | response = get_response(request)
  | File "/opt/app-root/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
  | response = self.process_response(request, response)
  | File "/opt/app-root/src/rbac/rbac/middleware.py", line 287, in process_response
  | if request.user:
  | AttributeError: 'WSGIRequest' object has no attribute 'user'

**To Reproduce**
From inside dev cluster
Pass the following x-rh-identity
"eyJpZGVudGl0eSI6eyJpbnRlcm5hbCI6eyJhdXRoX3RpbWUiOjAsImF1dGhfdHlwZSI6ImJhc2ljLWF1dGgiLCJvcmdfaWQiOiIxMTc4OTc3MiIsImFjY291bnRfbnVtYmVyIjoiNjA4OTcxOSIsInVzZXIiOnsiZmlyc3RfbmFtZSI6IkplZmYiLCJsYXN0X25hbWUiOiJOZWVkbGUiLCJpc19pbnRlcm5hbCI6ZmFsc2UsImlzX2FjdGl2ZSI6dHJ1ZSwibG9jYWxlIjoiZW5fVVMiLCJpc19vcmdfYWRtaW4iOnRydWUsInVzZXJuYW1lIjoiaW5zaWdodHMtcWEiLCJlbWFpbCI6ImpuZWVkbGUrcWFAcmVkaGF0LmNvbSIsInR5cGUiOiJVc2VyIiwiZW50aXRsZW1lbnRzIjp7Imluc2lnaHRzIjp7ImlzX2VudGl0bGVkIjp0cnVlLCJvcGVuc2hpZnQiOnsiaXNfZW50aXRsZWQiOnRydWV9LCJzbWFydF9tYW5hZ2VtZW50Ijp7ImlzX2VudGl0bGVkIjpmYWxzZX0sImh5YnJpZF9jbG91ZCI6eyJpc19lbnRpdGxlZCI6dHJ1ZX19fX19fX0="
**Expected behavior**
Incompatible header

**Screenshots**

**Context (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Commit Hash from status endpoint:

**Additional context**

**Comment by mkanoor** [comment]
The x-rh-identity data was off. Closing as User error
